### ISSUE TITLE
Documentation, Installation instructions (Part 2)

### ISSUE THREAD

**Issue by pschloss** [riffomonas/reproducible_research#15]
> With this module you have two sets of dependencies, one set for building the Jekyll website and another for working through the R and Reproducible Research (RR) Examples. I think it is appropriate to talk in detail about the Jekyll Build in the README and have the details of the R and RR dependencies in the module itself. As is the reader needs to dig a bit to find the dependencies in the module. In the "Dependencies to run tutorials" section of the README, include a link to the basic dependencies needed for the tutorials.

**Comment by pschloss** [comment]
I think this was addressed by #16

**Comment by tracykteal** [comment]
Agree, addressed.
