### ISSUE TITLE
Documentation, Example usage

### ISSUE THREAD

**Issue by pschloss** [riffomonas/reproducible_research#16]
> As I was going through this the first time it took me a while to completely grok how I was supposed to interact with the materials. At first I thought it was the slides, then the videos, then I realized that the slides have the transcript embedded, but that didn't come up until the last link of the Paper or several minutes into the first video. I think including an "Example Usage", "Quick Start", or "Tutorial Workflow" section that lays out, at a high level, how you would expect users of your tutorial to interact with the content would really help. Include here your target audience (and expected audiences experience level) and how long it should take users to complete the series. I think this makes most sense on the website itself, and not in the README.

**Comment by tracykteal** [comment]
Thanks. Those are really helpful. On the website I find the blue and yellow fonts difficult to read, particularly the yellow, but that may just be personal preference.

**Comment by pschloss** [comment]
The color issue has been addressed in #21
