### ISSUE TITLE
Pedagogy / Instructional design, Content scope and length

### ISSUE THREAD

**Issue by pschloss** [riffomonas/reproducible_research#17]
> As I was working on the review I was conflicted about whehter or not using HPC/AWS or local resources is best. After thinking on it some, I feel it is mostly a design choice and as such is acceptable to keep the focus on HPC/AWS implementations. That being said, I would like to see some additional information included about running these same tutorials using local resources. Main reason is that as is, you are expecting users to incur some cost to use the HPC/AWS resources when they could still learn most of the materials with a focus on local tools. Additionally, both approaches are non-trivial to get up and running and having some instruction for both would improve the tutorial and make it accesible for those that choose to use HPC/AWS or not.

**Comment by pschloss** [comment]
This is a great point that I grappled with in developing the materials. Ultimately, I came down on the side of using AWS because it was generalizable to the most people and because it allowed me to demonstrate how using AWS helps with reproducibility. Here are a few further thoughts on why I think the current emphasis on AWS is the best choice for this material and this audience:

* I have access to the University of Michigan HPC, but that is fairly unique to my institution and would not generalize to most people. Things like setting up accounts, using schedulers, and the availability and methods of loading software all vary by HPC. AWS provides a straightforward method to give all learners the same ecosystem in a pretty quick series of steps. As I discuss in the materials, this also emphasizes the value of tools like AWS for reproducibility since they could create an AMI of their environment that they could cite in a manuscript allowing anyone to load and work with their project.
* In my experience teaching this type of material to learners, I have found that many researchers do not have a straightforward way of gaining access to an HPC. Their institution may not have an HPC or it may take days/weeks to get an account.
* Alternatively, learners could work with the tools on their local computer. This again causes problems for installing dependencies and variation between operating systems. That is of course part of bioinformatics; however, I have found that the datasets that most people are generating these days are not readily analyzed on a laptop or desktop computer. The ability to do the analysis remotely is an important skill for people to develop.
* Yes, AWS does cost something, but it is pretty affordable and as I lay out in that session, it is much cheaper than upgrading hardware. Even if they were to use a local HPC, it is unlikely that would be free. The HPC at my institution is cheaper than AWS, but it still costs something.

**Comment by tracykteal** [comment]
These are all good points and validate the choice. You might even consider linking to this issue in a 'why do we use AWS' in the README

**Comment by jhollist** [comment]
I like @tracykteal suggestion.  Having some documentation of the deliberation would be instructive I think.

**Comment by pschloss** [comment]
Thanks for the suggestion, this was added in `a2ad7b1`
