### ISSUE TITLE
color of text on Riffomonas web site

### ISSUE THREAD

**Issue by tracykteal** [riffomonas/reproducible_research#21]
The color of the text on the Riffomonas website is a bit hard for me to read. The yellow font, and mouseover font, in particular is low contrast with the white background. I'm not sure if this is a personal preference or a more general readability issue though. Accessibility guidelines don't seem to recommend particular colors, but just emphasize contrast.

**Comment by pschloss** [comment]
The link color has been changed to a darker color. Thanks for the suggestion!
